# Generated by Django 2.0.4 on 2018-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qq', models.CharField(blank=True, max_length=12)),
                ('obj_school', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('is_enroll', models.BooleanField()),
                ('modifed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
