# Generated by Django 2.0.4 on 2018-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YuBaoMing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('need_dorm', models.CharField(max_length=4, verbose_name='酒店')),
                ('need_bus', models.CharField(max_length=4, verbose_name='大巴车')),
                ('need_lunch', models.CharField(max_length=4, verbose_name='午餐')),
                ('major', models.CharField(max_length=4, verbose_name='专业')),
                ('area', models.CharField(max_length=4, verbose_name='地点')),
            ],
            options={
                'verbose_name_plural': '12月预报名',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '文都直通车'},
        ),
        migrations.AlterModelOptions(
            name='student2',
            options={'verbose_name_plural': '文都现场确认'},
        ),
        migrations.AlterField(
            model_name='student2',
            name='is_return',
            field=models.CharField(max_length=40, verbose_name='单程/双程'),
        ),
        migrations.AlterField(
            model_name='student2',
            name='modifed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
