# Generated by Django 2.0.4 on 2018-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生报名信息表'},
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(max_length=100, verbose_name='所在学院'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_enroll',
            field=models.BooleanField(verbose_name='是否学员'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modifed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='信息提交时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='obj_school',
            field=models.CharField(max_length=100, verbose_name='目标学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
