# Generated by Django 2.0.4 on 2018-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20180928_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在学院'),
        ),
        migrations.AlterField(
            model_name='student',
            name='obj_school',
            field=models.CharField(blank=True, max_length=100, verbose_name='目标学校'),
        ),
    ]
