# Generated by Django 2.0.4 on 2018-11-09 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20181109_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='yubaoming',
            name='modifed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
    ]
