# Generated by Django 2.0.4 on 2018-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20181124_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yubaoming',
            name='area',
            field=models.CharField(choices=[('市区', '市区'), ('曹妃甸', '曹妃甸')], max_length=10, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='yubaoming',
            name='need_dorm',
            field=models.CharField(choices=[('单人间', '单人间'), ('双人间', '双人间')], max_length=10, verbose_name='酒店'),
        ),
        migrations.AlterField(
            model_name='yubaoming',
            name='need_lunch',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=10, verbose_name='午餐'),
        ),
    ]
