# Generated by Django 2.0.4 on 2018-12-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_yubaoming_is_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yubaoming',
            options={'verbose_name_plural': '12月正式报名'},
        ),
    ]
